name: Build Release

on:
  push:
    branches:
    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Clone custom items
      uses: actions/checkout@v2.3.4
      with:
        repository: Baystation12/custom-items
        path: custom-items
    - name: Build and Publish Image to Registry
      env:
        BUILD_ARGS: -Icustom-items/inc.dm
      uses: elgohr/Publish-Docker-Github-Action@f7aca2fea76a5218f3c76cd5933c3ba1d8008774
      with:
        name: ${{ secrets.IMAGE_NAME }}
        username: ${{ secrets.REG_USER }}
        password: ${{ secrets.REG_PASS }}
        tags: "latest"
        buildargs: BUILD_ARGS
        registry: ${{ secrets.REG_URL }}
        cache: true